<a href="https://colab.research.google.com/github/NyashaMasendeke/Deep-Learning/blob/main/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu121


In [ ]:
#tensors introduction
#tensors are used to represent data create using torch.tensor
#scalar tensor
scalar = torch.tensor(7)
scalar



tensor(7)

In [ ]:
scalar.ndim


0

In [ ]:
scalar.item()

7

In [ ]:
#creating a vector tensor
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#Matrix
Matrix = torch.tensor([[7,8],
                      [9,10]])
Matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
Matrix.ndim

2

In [ ]:
Matrix[1]


tensor([ 9, 10])

In [ ]:
Matrix.shape

torch.Size([2, 2])

In [ ]:
#Tensor
Tensor = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
Tensor


tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
Tensor.ndim

3

In [ ]:
Tensor.shape

torch.Size([1, 3, 3])

In [ ]:
#Research on dimensions of a tensor

In [ ]:
###Random tensors
#Random tensors are important because the way many neural nets
#learn is that they start with tensor full of rndom numbers and then
#adjust those random numbers to  better represent the data
#start with random numbers ---< look at data --> update random numbers ---> look at data
#---->update

In [ ]:
#Create a random tensor of size(3,4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[5.5018e-01, 9.3883e-01, 7.5233e-01, 7.1380e-01],
        [6.3737e-01, 6.0791e-04, 9.2014e-01, 7.3784e-03],
        [7.7487e-01, 7.3616e-02, 9.8629e-01, 3.9681e-01]])

In [ ]:
random_tensor.ndim

2

In [ ]:
#create a random tensor similar to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3))

In [ ]:
###zeros and ones tensor
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
#creating a range of tensors
#use torch.range()
one_to_ten = torch.arange(start=1, end=11, step=2)
one_to_ten

tensor([1, 3, 5, 7, 9])

In [ ]:
##tensor datatypes
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,#what is the datatype of your tensor
                               device=None,#what device is your tensor on
                               requires_grad=False
                               )
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
#3 big errors you will run into in pytorch and deeep learning
# 1. tensors no right datatype
# 2. tensors not right shape
# 3. tensors not on right device


In [ ]:
#research on precison computinng

In [ ]:
#getting information from tensors
#check shape  tensor.shape
#check device  tensor.device
#check datatype tensor.dtype

In [ ]:
#create a ensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.4014, 0.0486, 0.7416, 0.3725],
        [0.9356, 0.4665, 0.9990, 0.1539],
        [0.0992, 0.6239, 0.2027, 0.9781]])

In [ ]:
#manipulating tensors
#tensor operaations include  :
#addition, subtraction, division and multiplication


In [ ]:
#tensor addition
tensor = torch.tensor([1,2,3])
tensor +10

tensor([11, 12, 13])

In [ ]:
tensor * 10

tensor([10, 20, 30])

In [ ]:
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [ ]:
#matrix multiplication
#there are two ways to do multiplication in neural nets
#elementwise multiplication
#dot product


In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
#matrix multiolication in deep learning only works when the
#inner dimensions are the same or match
#rules of matrix multiplication
torch.matml(torch.rand(3,19), (torch.rand(2,3)))


In [ ]:
#there are shape errirors
tensora = torch.tensor([[1,2],
                       [3,4],
                       [5,6]])
tensorb = torch.tensor([[7,8],
                        [9,10],
                        [11,12]])

torch.matmul(tensora, tensorb)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensorb.T

tensor([[ 7,  9, 11],
        [ 8, 10, 12]])

In [ ]:
tensorb

tensor([[ 7,  8],
        [ 9, 10],
        [11, 12]])

In [ ]:
tensorb.T.shape

torch.Size([2, 3])

In [ ]:
#the matrix multiplication opertion works wen tensorb is transposed

torch.matmul(tensora, tensorb.T)

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

In [ ]:
#visualize visualize visualize


In [ ]:
#tensor aggregation mean , max, sum
#going frm a large amnt of numbers to a small number of numbers
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
#find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
#find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
#find the mean
#the torch.mean requires a tensor of type 32 datatype
torch.mean(x.type(torch.float32))

tensor(45.)

In [ ]:
#find the sum
torch.sum(x),  x.sum()

(tensor(450), tensor(450))

In [ ]:
##Finding the positional of min and max using argmin
#find the position in the tensor that has the minimum  value with argmin and returns index position of target tensor
x.argmin()

tensor(0)

In [ ]:
x[1]

tensor(10)

In [ ]:
#find the positional with the maximum alue using armax
x.argmax()

tensor(9)

##Reshaping stacking squeezing and unsqueezing tensors

*Reshaping - reshapes an input tensor to a defined shape
*View - Return a view of an input tensor of certain shape but keep the same memroy as the original tensor

*Stacking - combine multiple tensors on top of each other(vstack) or side by side (hedge stack )

*Squeeze - removes one dimeensions from a tensor

*Unsqueeze - add a 1 dimnesion to a target tensor

*Permute - return a view of the input with dimensions permuted(swapped ) in a certain way

In [ ]:
#The reshape has to compatible with the original size
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
#stacking tensors on top of each other
x_stacked = torch.stack([x, x, x], dim=1)
x_stacked

tensor([[1., 1., 1.],
        [2., 2., 2.],
        [3., 3., 3.],
        [4., 4., 4.],
        [5., 5., 5.],
        [6., 6., 6.],
        [7., 7., 7.],
        [8., 8., 8.],
        [9., 9., 9.]])


##Research vstack and hstack

##Indexing (Selecting data from tensors)

In [ ]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
x.shape

torch.Size([1, 3, 3])

In [ ]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0][0]

tensor([1, 2, 3])

In [ ]:
x[0][0][0]

tensor(1)

##Pytorch tensors and numpy

Numpy is a popular scientific python numerical computing library
Pytorch has functionality to interact with it

*Data in numpy , want in pytorch tensor ->torch.from_numpy(ndarray)

*Pytorch tensor -> Numpy -> torch.Tensor.numpy



In [ ]:
#numpy array to tensor
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)#.type(torch.float32)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
#change the value of the array
array = array + 1
array, tensor



array([3., 4., 5., 6., 7., 8., 9.])

In [ ]:
#NOTE ::
#default numpy datatype is float64
#default pytoech datatype is float32

##PYTORCH REPRODUCEBILITY

In [ ]:
#trying to take random out of random
torch.rand(3,3)

tensor([[0.6567, 0.6159, 0.4026],
        [0.6851, 0.5215, 0.8792],
        [0.0662, 0.7274, 0.5897]])

In [ ]:
#to reduce the randomness in pytorch and neeural networks comes the concept of random seed


In [ ]:
#creare two random tensors
random_tensor_a = torch.rand(3,4)
random_tensor_b = torch.rand(3,4)
print(random_tensor_a)
print(random_tensor_b)
print(random_tensor_a == random_tensor_b)

tensor([[0.0091, 0.5795, 0.3666, 0.7618],
        [0.8005, 0.5476, 0.8233, 0.7395],
        [0.7330, 0.0528, 0.4376, 0.2755]])
tensor([[0.1904, 0.7022, 0.7854, 0.2685],
        [0.4480, 0.5801, 0.4571, 0.0721],
        [0.1009, 0.0337, 0.3586, 0.6387]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
#lets make some random but reproducible TENSORS


#set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)#a way to flavour the randomness

random_tensor_c = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)

random_tensor_d = torch.rand(3, 4)

print(random_tensor_c)
print(random_tensor_d)
print(random_tensor_c == random_tensor_d)



tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


##Putting tensors and models on a GPU

*GPUS ALLOW FOR FASTER OPERATIONS


In [ ]:
tensor = torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

In [ ]:
#move tensor to GPU (IF AVAILABLE)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

##MOVING TENSORS TO CPU

In [ ]:
## YOU CAN USE SEVERAL GPUS FOR SEVERAL TENSORS AND MODELS
#ON DIFFERENT GPUS

#Saving And Loading a Model
##torch.save()--saves a pytorch object in a pickle format
##torch.load()---loads a saved  pytorch object
##torch.nn.Module.load_state_dict ()---allows you to load a models saved state dictionary


In [ ]:
#Saving and loading model
from pathlib import Path
#Create a models dir
MODEL_PATH = Path("models")
MODEL_PATH.mkdir(parents=True,)

#Create a model save path
MODEL_NAME = ""
MODEL_SAVE_PATH =

#SAVE MODEL STATE_DICT
torch.save()

#loading pytorch model
#create a new instance of state_dict
#to load in a saved state dict create an instance of the model
torch.load()


#Making predictions


In [ ]:
loaded_model_0.eval()
with torch.inference_mode():
  loaded_model_preds = loaded_model_0(X_test)
loaded_model_preds